### PR TITLE
Create japanese.yml

### PR DESCRIPTION
**Pull request by 6gatu6kaniUFOga-mc**
add Japanese lang

### CODE REVIEW

**Comment by 6gatu6kaniUFOga-mc** [comment]
New lang type

**Comment by karlovm** [comment]
The file is not complete. Please resubmit full transltaion

**Comment by 6gatu6kaniUFOga-mc** [comment]
> ファイルが完了していません。完全な翻訳を再送信してください

What not translate?

**Comment by karlovm** [comment]
image
You're missing end of file

**Comment by 6gatu6kaniUFOga-mc** [comment]
I make new lang file
I add today after noon

**Comment by karlovm** [comment]
Nice!

**Comment by 6gatu6kaniUFOga-mc** [comment]
I fix yml

**Comment by karlovm** [comment]
Looks like working solution. Thanks!

**Pull request merged**
